"""Per-user preference learning — features, the Bayesian model,
axis-varied candidates, the critic's use of a learned model, and the
retrain-after-every-tap routine (against real Postgres)."""

from __future__ import annotations

import os
import subprocess
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

import numpy as np
import psycopg
import pytest
from dotenv import find_dotenv, load_dotenv
from psycopg.rows import dict_row

from app.llm import routing
from app.nodes.critic import choose_best_for_panel
from app.preference import model
from app.preference.axes import AXES, levels_for_candidate, plan_for_panel, variant_prompt
from app.preference.features import DEFAULT_SCALES, FEATURES, feature_vector, pixel_features
from app.preference.notes import NOTES_MIN_DAYS, TasteNotes, is_due, maybe_refresh_notes
from app.preference.retrain import MIN_EDGE, MIN_TAPS, rebuild_preference, should_activate
from app.preference.state import PreferenceState, load_preference_state
from contracts import Candidate, ImagePrompt

pytestmark = pytest.mark.enable_socket

REPO_ROOT = Path(__file__).resolve().parents[3]
TEST_SCHEMA = "comiccanvas_test_preference"
WARMTH = FEATURES.index("warmth")


# --- features ---------------------------------------------------------------


def _solid(bgr: tuple[int, int, int]) -> np.ndarray:
    return np.full((100, 100, 3), bgr, dtype=np.uint8)


def test_warmth_is_positive_for_orange_and_negative_for_blue() -> None:
    warm = pixel_features(_solid((40, 120, 230)), None)["warmth"]  # BGR: orange-ish
    cool = pixel_features(_solid((230, 120, 40)), None)["warmth"]
    assert warm > 0.5 and cool < -0.5


def test_closeness_grows_with_the_face_share_of_the_frame() -> None:
    img = _solid((128, 128, 128))
    assert pixel_features(img, None)["closeness"] == 0.0
    small = pixel_features(img, (40, 40, 60, 60))["closeness"]
    big = pixel_features(img, (10, 10, 90, 90))["closeness"]
    assert 0.0 < small < big <= 1.0


def test_feature_vector_needs_every_measured_feature() -> None:
    complete = {f: 0.5 for f in FEATURES if f != "expression"}
    assert feature_vector(complete) is not None
    assert feature_vector({k: v for k, v in complete.items() if k != "warmth"}) is None


# --- model ------------------------------------------------------------------


def _planted_diffs(n: int, rng: np.random.Generator, true_w: np.ndarray) -> np.ndarray:
    """Taps generated by a person whose true taste is `true_w`."""
    x = rng.normal(size=(n, len(true_w)))
    picks_first = rng.random(n) < model.sigmoid(x @ true_w)
    return np.where(picks_first[:, None], x, -x)  # always chosen-minus-rejected


def test_model_recovers_a_planted_preference_and_gets_more_certain() -> None:
    true_w = np.zeros(len(FEATURES))
    true_w[WARMTH] = 2.0
    rng = np.random.default_rng(0)
    diffs = _planted_diffs(80, rng, true_w)

    _, cov_few = model.fit(diffs[:8])
    mu_many, cov_many = model.fit(diffs)

    assert mu_many[WARMTH] > 1.0  # found the planted taste
    assert np.argmax(np.abs(mu_many)) == WARMTH
    assert cov_many[WARMTH, WARMTH] < cov_few[WARMTH, WARMTH]  # more taps -> less unsure


def test_no_taps_returns_the_prior_and_an_unsure_model_predicts_near_a_coin_flip() -> None:
    mu, cov = model.fit(np.zeros((0, len(FEATURES))))
    assert np.allclose(mu, 0) and np.allclose(cov, np.eye(len(FEATURES)))
    assert model.predict_prob(mu, cov, np.ones(len(FEATURES))) == pytest.approx(0.5)


def test_thompson_samples_vary_but_center_on_the_mean() -> None:
    mu = np.arange(len(FEATURES), dtype=float)
    cov = np.eye(len(FEATURES)) * 0.25
    rng = np.random.default_rng(1)
    draws = np.array([model.sample_weights(mu, cov, rng) for _ in range(2000)])
    assert draws.std(axis=0).min() > 0.3
    assert np.allclose(draws.mean(axis=0), mu, atol=0.1)


# --- axes -------------------------------------------------------------------


def _prompt() -> ImagePrompt:
    return ImagePrompt(
        panel_id=1,
        generator="mock",
        character_clause="a man",
        environment_clause="a gym",
        positive="a man in a gym",
        negative="blurry",
        seed=100,
        guidance=None,
        steps=None,
    )


def test_four_panels_spread_across_all_three_axes() -> None:
    axes = [plan_for_panel(pid).axis for pid in (1, 2, 3, 4)]
    assert set(axes) == set(AXES) and axes[0] == axes[3]


def test_once_it_has_taps_the_most_uncertain_axis_is_explored_first() -> None:
    z = {"warmth": 3.0, "closeness": 0.1, "expression": 1.0}  # closeness is least certain
    assert plan_for_panel(1, z=z, n_taps=10).axis == "closeness"
    assert plan_for_panel(1, z=z, n_taps=2).axis == AXES[0]  # too few taps to trust z


def test_three_candidates_differ_on_exactly_one_axis_and_keep_base_plus_k_seeds() -> None:
    plan = plan_for_panel(1)  # warmth
    made = [variant_prompt(_prompt(), plan, k) for k in range(3)]
    levels = [preset["axis_level"] for _, preset in made]
    assert levels == [-1.0, 0.0, 1.0]
    assert [v.seed for v, _ in made] == [100, 101, 102]
    assert len({v.positive for v, _ in made}) == 3
    # Every option speaks about the varied knob, level 0 included (a neutral phrase) — a bare
    # "as usual" against phrased variants would otherwise read as "any phrase beats none".
    assert made[1][0].positive.endswith("Also: a balanced, neutral color palette.")
    assert "cool" in made[0][0].positive and "warm" in made[2][0].positive
    assert all(preset["phrased"] == 1.0 for _, preset in made)


def test_knobs_that_are_not_being_varied_are_not_spoken_to_at_level_zero() -> None:
    plan = plan_for_panel(1)  # varies warmth
    positive = variant_prompt(_prompt(), plan, 1)[0].positive
    assert "palette" in positive and "view" not in positive and "expression" not in positive


def test_a_learned_lean_is_baked_into_every_candidate_but_they_still_vary() -> None:
    plan = plan_for_panel(
        2, lean={"warmth": 1, "closeness": 0, "expression": 0}
    )  # explores closeness
    assert plan.axis == "closeness"
    for k in range(3):
        assert levels_for_candidate(plan, k)["warmth"] == 1
        assert "warm color palette" in variant_prompt(_prompt(), plan, k)[0].positive
    assert [levels_for_candidate(plan, k)["closeness"] for k in range(3)] == [-1, 0, 1]


# --- critic -----------------------------------------------------------------


def _cand(cid: str, warmth: float, identity: float = 0.8) -> Candidate:
    scores = {f: 0.5 for f in FEATURES}
    scores.update({"warmth": warmth, "identity": identity, "expression": 0.0})
    return Candidate(id=cid, panel_id=1, url=f"http://x/{cid}.png", seed=1, scores=scores)


def _state(mu_warmth: float, sd: float, *, active: bool = True) -> PreferenceState:
    mu = np.zeros(len(FEATURES))
    mu[WARMTH] = mu_warmth
    return PreferenceState(
        mu=mu,
        cov=np.eye(len(FEATURES)) * sd**2,
        scales=np.array([DEFAULT_SCALES[f] for f in FEATURES]),
        n_taps=30,
        active=active,
    )


async def _no_retry(_: int) -> list[Candidate]:
    raise AssertionError("no retry expected")


async def test_an_active_confident_model_picks_the_warmest_and_records_rewards() -> None:
    cands = [_cand("cool", 0.0), _cand("mid", 0.10), _cand("warm", 0.30)]
    final, _ = await choose_best_for_panel(
        1, cands, regenerate=_no_retry, preference=_state(3.0, 1e-3), rng=np.random.default_rng(0)
    )
    chosen = next(c for c in final if c.chosen)
    assert chosen.id == "warm"
    assert chosen.scores["explored"] == 0.0
    rewards = {c.id: c.scores["reward"] for c in final}
    assert rewards["warm"] > rewards["mid"] > rewards["cool"]  # runner-up ordering for the A/B pair


async def test_an_inactive_model_changes_nothing() -> None:
    a, b = _cand("a", 0.0, identity=0.9), _cand("b", 0.9, identity=0.7)
    with_pref, _ = await choose_best_for_panel(
        1,
        [a.model_copy(deep=True), b.model_copy(deep=True)],
        regenerate=_no_retry,
        preference=_state(3.0, 1e-3, active=False),
    )
    without, _ = await choose_best_for_panel(
        1, [a.model_copy(deep=True), b.model_copy(deep=True)], regenerate=_no_retry
    )
    assert next(c.id for c in with_pref if c.chosen) == next(c.id for c in without if c.chosen)


async def test_an_unsure_model_sometimes_explores_and_flags_it() -> None:
    explored = 0
    for seed in range(60):
        cands = [_cand("a", 0.10), _cand("b", 0.12)]
        final, _ = await choose_best_for_panel(
            1,
            cands,
            regenerate=_no_retry,
            preference=_state(0.1, 3.0),
            rng=np.random.default_rng(seed),
        )
        explored += int(next(c for c in final if c.chosen).scores["explored"])
    assert 5 < explored < 55  # neither never nor always


# --- retrain against real Postgres -------------------------------------------


@pytest.fixture(scope="module")
def database_url() -> Iterator[str]:
    load_dotenv(find_dotenv(usecwd=True))
    url = os.environ.get("DATABASE_URL")
    if not url:
        pytest.skip("DATABASE_URL not configured")
    with psycopg.connect(url, autocommit=True) as conn:
        conn.execute(f'DROP SCHEMA IF EXISTS "{TEST_SCHEMA}" CASCADE')
    env = {**os.environ, "DB_SCHEMA": TEST_SCHEMA}
    subprocess.run(["uv", "run", "alembic", "upgrade", "head"], cwd=REPO_ROOT, env=env, check=True)
    yield url
    with psycopg.connect(url, autocommit=True) as conn:
        conn.execute(f'DROP SCHEMA IF EXISTS "{TEST_SCHEMA}" CASCADE')


@pytest.fixture
def conn(database_url: str) -> Iterator[psycopg.Connection[Any]]:
    c = psycopg.connect(database_url, row_factory=dict_row)
    c.execute(f'SET search_path TO "{TEST_SCHEMA}", public')
    c.execute("TRUNCATE users CASCADE")
    c.commit()
    yield c
    c.close()


def _seed_taps(
    conn: psycopg.Connection[Any], user_id: str, n: int, prefer: str, rng: np.random.Generator
) -> None:
    """`n` days, one panel each, two candidates with random features; the
    tapped one is the warmer (`prefer="warmth"`) or the hand-set reward's
    favourite (`prefer="hand"`)."""
    conn.execute("INSERT INTO users (id, email) VALUES (%s, NULL)", (user_id,))
    start = datetime(2026, 9, 1, tzinfo=UTC)
    for i in range(n):
        job = f"{user_id}:{i}"
        conn.execute(
            "INSERT INTO jobs (id, user_id, kind, status) VALUES (%s,%s,'daily','done')",
            (job, user_id),
        )
        conn.execute(
            "INSERT INTO days (job_id, user_id, date, source) VALUES (%s,%s,%s,'text')",
            (job, user_id, (start + timedelta(days=i)).date()),
        )
        conn.execute(
            "INSERT INTO beats (day_id, beat_id, time, place, event, emotion, importance, humor) "
            "VALUES (%s,'b1','morning','desk','e','calm',0.5,0.5)",
            (job,),
        )
        conn.execute(
            "INSERT INTO panels (day_id, panel_id, beat_id, place, time_of_day, expression, "
            "action, framing, caption_a) "
            "VALUES (%s,1,'b1','desk','morning','neutral','a','wide','c')",
            (job,),
        )
        pair: list[dict[str, float]] = []
        for j in range(2):
            scores = {
                f: float(rng.uniform(0.2, 0.9)) for f in FEATURES[:10]
            }  # critic + pixel + axis
            scores["expression"] = 0.0
            pair.append(scores)
            conn.execute(
                "INSERT INTO candidates (id, day_id, panel_id, url, seed, scores) "
                "VALUES (%s,%s,1,%s,%s,%s)",
                (f"{job}-{j}", job, f"http://x/{job}-{j}.png", j, psycopg.types.json.Json(scores)),
            )
        if prefer == "warmth":
            win = 0 if pair[0]["warmth"] > pair[1]["warmth"] else 1
        else:
            from app.critic.reward_head import score

            def hand(s: dict[str, float]) -> float:
                return score(Candidate(id="t", panel_id=1, url="u", seed=1, scores=s))

            win = 0 if hand(pair[0]) > hand(pair[1]) else 1
        conn.execute(
            "INSERT INTO image_pairs (day_id, panel_id, chosen, rejected, source, created_at) "
            "VALUES (%s,1,%s,%s,'ab',%s)",
            (
                job,
                f"http://x/{job}-{win}.png",
                f"http://x/{job}-{1 - win}.png",
                start + timedelta(days=i, hours=1),
            ),
        )
    conn.commit()


def test_a_person_who_likes_warm_images_gets_an_active_ranking_model(
    conn: psycopg.Connection[Any],
) -> None:
    _seed_taps(conn, "u-warm", 40, "warmth", np.random.default_rng(3))

    summary = rebuild_preference(conn, "u-warm")
    conn.commit()

    assert summary["n_taps"] == 40
    assert summary["active"] is True  # beat the hand-set weights on held-out taps
    assert summary["accuracy"]["learned"] > summary["accuracy"]["hand"]
    state = load_preference_state(conn, "u-warm")
    # (`lean` is the knob model's, not this model's: these candidates carry no knob levels,
    # so it has nothing to learn from — see the best-of-3 tests below.)
    assert (
        state is not None
        and state.active
        and state.lean
        == {
            "warmth": 0,
            "closeness": 0,
            "expression": 0,
        }
    )
    snaps = conn.execute(
        "SELECT tap_index, prob, correct FROM preference_snapshots WHERE user_id='u-warm' "
        "ORDER BY tap_index"
    ).fetchall()
    assert [s["tap_index"] for s in snaps] == list(range(1, 41))
    assert np.mean([s["correct"] for s in snaps[-15:]]) >= 0.75  # late taps predicted well


def test_the_learned_model_does_not_replace_hand_set_weights_when_it_cannot_beat_them(
    conn: psycopg.Connection[Any],
) -> None:
    _seed_taps(conn, "u-hand", 40, "hand", np.random.default_rng(4))  # hand-set is already perfect
    summary = rebuild_preference(conn, "u-hand")
    assert summary["n_taps"] == 40
    assert summary["accuracy"]["hand"] == pytest.approx(1.0)
    assert summary["active"] is False


def test_too_few_taps_never_activates_and_rebuild_is_idempotent(
    conn: psycopg.Connection[Any],
) -> None:
    _seed_taps(conn, "u-few", MIN_TAPS - 5, "warmth", np.random.default_rng(5))
    first = rebuild_preference(conn, "u-few")
    second = rebuild_preference(conn, "u-few")
    conn.commit()
    assert first["active"] is False and second == first
    n = conn.execute(
        "SELECT count(*) AS n FROM preference_snapshots WHERE user_id='u-few'"
    ).fetchone()
    assert n is not None and n["n"] == MIN_TAPS - 5


def test_only_the_latest_pick_for_a_panel_counts(conn: psycopg.Connection[Any]) -> None:
    _seed_taps(conn, "u-flip", 6, "warmth", np.random.default_rng(6))
    job = "u-flip:0"
    conn.execute(  # the person changes their mind about panel 1 of day 0
        "INSERT INTO image_pairs (day_id, panel_id, chosen, rejected, source) "
        "VALUES (%s,1,%s,%s,'ab')",
        (job, f"http://x/{job}-0.png", f"http://x/{job}-1.png"),
    )
    conn.commit()
    assert rebuild_preference(conn, "u-flip")["n_taps"] == 6  # not 7


def test_thompson_seed_is_stable_across_processes() -> None:
    """`hash()` is randomized per process; a resumed job must re-pick alike."""
    import subprocess
    import sys

    from app.nodes.critic import _stable_seed

    code = "from app.nodes.critic import _stable_seed; print(_stable_seed('job-1:2026-09-19', 3))"
    out = subprocess.run(
        [sys.executable, "-c", code],
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO_ROOT / "services" / "worker",
    ).stdout.strip()
    assert int(out) == _stable_seed("job-1:2026-09-19", 3)


def test_a_single_lucky_tap_does_not_activate_the_model() -> None:
    """The gate used to be "strictly more accurate than the default" — on ~20 scored
    taps that flipped on from ONE lucky call (a 71% score on 21 taps carries a 95%
    margin of about +-20 points). It now needs a clear net edge."""
    assert not should_activate(n_taps=25, edge=1.0)  # one tap ahead: luck
    assert not should_activate(n_taps=25, edge=MIN_EDGE - 0.5)
    assert should_activate(n_taps=25, edge=MIN_EDGE)
    assert not should_activate(n_taps=MIN_TAPS - 1, edge=10.0)  # a big edge on too few taps
    assert not should_activate(n_taps=30, edge=-4.0)  # behind the default


def test_the_accuracy_summary_carries_every_number_the_page_shows(
    conn: psycopg.Connection[Any],
) -> None:
    """The page's "won X calls / net edge / matched the default on ALL taps" text is
    only honest if it is computed, not guessed — including the warm-up taps the
    head-to-head skips."""
    _seed_taps(conn, "u-summary", 30, "warmth", np.random.default_rng(9))

    acc = rebuild_preference(conn, "u-summary")["accuracy"]

    assert acc["overall_n"] == 30 and 0.0 <= acc["overall_hand"] <= 1.0
    assert acc["n_eval"] == 30 - acc["warmup"]
    # edge is exactly (calls the learned model won) - (calls the default won), ties half
    assert acc["edge"] == pytest.approx(
        acc["learned_wins"] - acc["hand_wins"], abs=acc["n_eval"] / 2
    )
    assert acc["min_edge"] == MIN_EDGE


def _gradient_norm(diffs: np.ndarray, w: np.ndarray) -> float:
    """Size of the posterior's gradient at `w`. The problem is convex, so a (near-)zero
    gradient proves `w` is THE optimum — no second optimizer needed to check against."""
    p = model.sigmoid(diffs @ w)
    return float(np.linalg.norm(-(diffs.T @ (1.0 - p)) + w / model.PRIOR_VAR))


@pytest.mark.parametrize("seed", [3, 13, 33, 57])  # people the old warm-started fit broke
def test_refitting_after_every_tap_reaches_the_true_optimum(seed: int) -> None:
    """Retraining after each tap warm-starts from the previous answer, and
    an undamped Newton step can overshoot and get stuck at a bad local
    point instead of the true optimum. These four seeds reproduce that
    failure mode; the fit must reach the true optimum regardless."""
    rng = np.random.default_rng(seed)
    n, d = 26, len(FEATURES)
    true = rng.normal(0, 2.0, d)  # a person with strong tastes
    x = rng.normal(0, 1.6, (n, d))
    picked_first = rng.random(n) < model.sigmoid(x @ true)
    diffs = np.where(picked_first[:, None], x, -x)

    mu = np.zeros(d)
    for t in range(1, n + 1):  # exactly what `rebuild_preference` does
        mu, _ = model.fit(diffs[:t], w0=mu)

    assert (
        _gradient_norm(diffs, mu) < 1e-4
    )  # a stationary point of a convex objective = the optimum
    assert np.abs(mu).max() < 8  # and never the +-15..20 garbage
    cold, _ = model.fit(diffs)
    assert np.allclose(mu, cold, atol=1e-4)  # warm-started and cold-started agree


def test_the_fit_never_increases_its_own_objective() -> None:
    """Whatever it is warm-started from — even a wild start — a step is only taken if it
    lowers the (convex) objective, so the answer can never be worse than where it began."""
    rng = np.random.default_rng(0)
    diffs = rng.normal(0, 2.0, (25, len(FEATURES)))
    wild = rng.normal(0, 15.0, len(FEATURES))

    def objective(w: np.ndarray) -> float:
        return float(np.sum(np.logaddexp(0.0, -(diffs @ w))) + 0.5 * float(w @ w))

    mu, _ = model.fit(diffs, w0=wild)

    assert objective(mu) <= objective(wild)
    assert _gradient_norm(diffs, mu) < 1e-4


# --- best-of-3 taps, the knob model, the KPI ---------------------------------------------


_EMBED_MIX = np.random.default_rng(99).normal(size=(4, 32))


def _seed_best_of_three(
    conn: psycopg.Connection[Any],
    user_id: str,
    n: int,
    choose: Any,
    rng: np.random.Generator,
    *,
    start: datetime = datetime(2026, 9, 1, tzinfo=UTC),
    pick_feature: str | None = None,
    pick_embedding: bool = False,
    roles: bool = False,
) -> None:
    """`n` days, one panel each, three candidates that differ only in warmth level (-1/0/+1)
    exactly as the generator makes them; `choose(levels, rng)` returns which one is picked.
    A tap writes one `image_pairs` row per option passed on, sharing a `tap_id`."""
    conn.execute("INSERT INTO users (id, email) VALUES (%s, NULL)", (user_id,))
    for i in range(n):
        job = f"{user_id}:{i}"
        conn.execute(
            "INSERT INTO jobs (id, user_id, kind, status) VALUES (%s,%s,'daily','done')",
            (job, user_id),
        )
        conn.execute(
            "INSERT INTO days (job_id, user_id, date, source) VALUES (%s,%s,%s,'text')",
            (job, user_id, (start + timedelta(days=i)).date()),
        )
        conn.execute(
            "INSERT INTO beats (day_id, beat_id, time, place, event, emotion, importance, humor) "
            "VALUES (%s,'b1','morning','desk','e','calm',0.5,0.5)",
            (job,),
        )
        conn.execute(
            "INSERT INTO panels (day_id, panel_id, beat_id, place, time_of_day, expression, "
            "action, framing, caption_a) "
            "VALUES (%s,1,'b1','desk','morning','neutral','a','wide','c')",
            (job,),
        )
        levels = [-1, 0, 1]
        feature_values: list[float] = []
        latents: list[float] = []
        for j, level in enumerate(levels):
            scores = {
                f: float(rng.uniform(0.2, 0.9)) for f in FEATURES[:10]
            }  # critic + pixel + axis
            if pick_feature is not None:
                feature_values.append(scores[pick_feature])
            scores.update(
                {
                    "axis_id": 0.0,
                    "axis_level": float(level),
                    "offset": float(level),
                    "level_warmth": float(level),
                    "level_closeness": 0.0,
                    "level_expression": 0.0,
                    "expression": 0.0,
                    "phrased": 1.0,
                }
            )
            if roles:  # the bandit's design: the guess (0) between two exploratory draws (1, 2)
                scores["role"] = float((1, 0, 2)[j])
            embedding_json = None
            if pick_embedding:  # a low-rank "image embedding": 4 hidden factors spread over 32 dims
                latent = rng.normal(size=4)
                latents.append(float(latent[0]))
                vector = latent @ _EMBED_MIX + rng.normal(scale=0.05, size=32)
                embedding_json = psycopg.types.json.Json([round(float(x), 5) for x in vector])
            conn.execute(
                "INSERT INTO candidates (id, day_id, panel_id, url, seed, scores, embedding) "
                "VALUES (%s,%s,1,%s,%s,%s,%s)",
                (
                    f"{job}-{j}",
                    job,
                    f"http://x/{job}-{j}.png",
                    j,
                    psycopg.types.json.Json(scores),
                    embedding_json,
                ),
            )
        pick = choose(levels, rng)
        if pick_embedding:
            pick = int(np.argmax(latents))
        if pick_feature is not None:  # a taste for a measured feature instead of a knob level
            pick = int(np.argmax(feature_values))
        for j in range(3):
            if j != pick:
                conn.execute(
                    "INSERT INTO image_pairs (day_id, panel_id, chosen, rejected, source, tap_id, "
                    "created_at) VALUES (%s,1,%s,%s,'ab',%s,%s)",
                    (
                        job,
                        f"http://x/{job}-{pick}.png",
                        f"http://x/{job}-{j}.png",
                        f"tap-{job}",
                        start + timedelta(days=i, hours=1),
                    ),
                )
    conn.commit()


def _warmest(levels: list[int], rng: np.random.Generator) -> int:
    return int(np.argmax(levels))


def test_a_best_of_three_tap_is_one_tap_that_remembers_every_option_passed_on(
    conn: psycopg.Connection[Any],
) -> None:
    _seed_best_of_three(conn, "u-b3", 6, _warmest, np.random.default_rng(1))

    summary = rebuild_preference(conn, "u-b3")
    conn.commit()

    assert summary["n_taps"] == 6  # six taps, not twelve rows
    snaps = conn.execute(
        "SELECT chosen_url, rejected_urls, default_picked FROM preference_snapshots "
        "WHERE user_id = 'u-b3' ORDER BY tap_index"
    ).fetchall()
    assert len(snaps) == 6
    assert all(len(s["rejected_urls"]) == 2 for s in snaps)
    assert all(s["chosen_url"].endswith("-2.png") for s in snaps)  # the warmest, level +1
    assert all(s["default_picked"] is False for s in snaps)


def test_the_ranking_model_learns_a_taste_for_a_measured_feature_from_best_of_three_picks(
    conn: psycopg.Connection[Any],
) -> None:
    """Predicting the favourite of THREE options (not just a pair) must beat chance (a third)
    once the person's picks follow a measured feature, and learn a positive weight for it."""
    _seed_best_of_three(
        conn, "u-feat", 60, _warmest, np.random.default_rng(8), pick_feature="warmth"
    )
    summary = rebuild_preference(conn, "u-feat")
    conn.commit()
    assert summary["accuracy"]["learned"] > 0.7  # chance is 1/3
    row = conn.execute("SELECT mu FROM preference_models WHERE user_id='u-feat'").fetchone()
    assert row is not None
    weights = dict(zip(FEATURES, row["mu"], strict=True))
    assert weights["warmth"] == max(weights.values()) and weights["warmth"] > 0.5


def test_a_person_who_always_picks_the_warmer_option_gets_a_warmer_default(
    conn: psycopg.Connection[Any],
) -> None:
    _seed_best_of_three(conn, "u-warmer", 40, _warmest, np.random.default_rng(2))

    summary = rebuild_preference(conn, "u-warmer")
    conn.commit()

    assert summary["lean"]["warmth"] >= 1
    assert summary["lean"]["closeness"] == 0 and summary["lean"]["expression"] == 0
    state = load_preference_state(conn, "u-warmer")
    assert state is not None and state.lean["warmth"] >= 1
    assert set(state.knob_uncertainty) == set(AXES)
    stored = conn.execute("SELECT knobs FROM preference_models WHERE user_id='u-warmer'").fetchone()
    assert stored is not None and set(stored["knobs"]["curves"]) == set(AXES)
    assert len(stored["knobs"]["curves"]["warmth"]) == 5  # levels -2..2


def test_a_person_with_no_preference_never_gets_a_default_beyond_what_they_were_shown(
    conn: psycopg.Connection[Any],
) -> None:
    def coin_flip(levels: list[int], rng: np.random.Generator) -> int:
        return int(rng.integers(3))

    _seed_best_of_three(conn, "u-flat", 60, coin_flip, np.random.default_rng(7))
    summary = rebuild_preference(conn, "u-flat")
    # (Coin flips can, rarely, look like a taste — `test_knobs.py` measures how rarely.
    # Whatever happens, a default never runs to a level that was never on screen.)
    assert max(abs(v) for v in summary["lean"].values()) <= 1


def test_the_default_pick_rate_is_recorded_against_its_chance_level(
    conn: psycopg.Connection[Any],
) -> None:
    def middle(levels: list[int], rng: np.random.Generator) -> int:
        return 1  # always the untouched default

    _seed_best_of_three(conn, "u-default", 8, middle, np.random.default_rng(3))
    accuracy = rebuild_preference(conn, "u-default")["accuracy"]
    assert accuracy["default_pick"] == pytest.approx(1.0)
    assert accuracy["default_pick_n"] == 8
    assert accuracy["default_pick_chance"] == pytest.approx(1 / 3)


def test_switching_personalisation_off_hides_the_lean_and_the_notes(
    conn: psycopg.Connection[Any],
) -> None:
    _seed_best_of_three(conn, "u-off", 40, _warmest, np.random.default_rng(2))
    rebuild_preference(conn, "u-off")
    conn.execute(
        "UPDATE preference_models SET notes = %s WHERE user_id = 'u-off'",
        (
            psycopg.types.json.Json(
                {"items": ["Prefers warm colours."], "updated_at": "2026-10-01"}
            ),
        ),
    )
    conn.commit()
    on = load_preference_state(conn, "u-off")
    assert on is not None and on.lean["warmth"] >= 1 and on.notes == ["Prefers warm colours."]

    conn.execute("INSERT INTO settings (user_id, personalise) VALUES ('u-off', false)")
    conn.commit()
    off = load_preference_state(conn, "u-off")
    assert off is not None and off.lean == {} and off.notes == []
    assert off.n_taps == on.n_taps  # it keeps learning; only its influence is off


def test_older_taps_count_for_less_so_a_changed_taste_is_followed(
    conn: psycopg.Connection[Any],
) -> None:
    """80 taps preferring cooler, then 60 preferring warmer: without forgetting the 80 outvote
    the 60; with it the model follows the recent taste."""

    def switching(levels: list[int], rng: np.random.Generator) -> int:
        switching.calls += 1  # type: ignore[attr-defined]
        return int(np.argmin(levels)) if switching.calls <= 80 else int(np.argmax(levels))  # type: ignore[attr-defined]

    switching.calls = 0  # type: ignore[attr-defined]
    _seed_best_of_three(conn, "u-switch", 140, switching, np.random.default_rng(4))
    rebuild_preference(conn, "u-switch")
    stored = conn.execute("SELECT knobs FROM preference_models WHERE user_id='u-switch'").fetchone()
    assert stored is not None
    curve = {p["level"]: p["mean"] for p in stored["knobs"]["curves"]["warmth"]}
    assert curve[1.0] > curve[-1.0]  # follows the recent (warmer) taste


# --- taste notes -------------------------------------------------------------------------


def test_notes_are_only_due_after_enough_taps_over_enough_days_and_once_a_week() -> None:
    now = datetime(2026, 10, 20, tzinfo=UTC)
    long_ago = now - timedelta(days=NOTES_MIN_DAYS + 1)
    assert not is_due(n_taps=10, first_tap_at=long_ago, notes_updated_at=None, now=now)
    assert not is_due(
        n_taps=40, first_tap_at=now - timedelta(days=3), notes_updated_at=None, now=now
    )
    assert not is_due(n_taps=40, first_tap_at=None, notes_updated_at=None, now=now)
    assert is_due(n_taps=40, first_tap_at=long_ago, notes_updated_at=None, now=now)
    assert not is_due(
        n_taps=40, first_tap_at=long_ago, notes_updated_at=now - timedelta(days=2), now=now
    )
    assert is_due(
        n_taps=40, first_tap_at=long_ago, notes_updated_at=now - timedelta(days=8), now=now
    )


async def test_notes_are_written_once_due_and_not_rewritten_within_a_week(
    conn: psycopg.Connection[Any], monkeypatch: pytest.MonkeyPatch
) -> None:
    routing.reset_provider_cache()
    monkeypatch.setenv("LLM_PROMPTS", "mock:mock-notes")
    provider, _ = routing.resolve("prompts")
    provider.set_structured_response(  # type: ignore[attr-defined]
        "TasteNotes", TasteNotes(notes=["Prefers warm colours."]).model_dump_json()
    )
    _seed_best_of_three(conn, "u-notes", 40, _warmest, np.random.default_rng(2))
    rebuild_preference(conn, "u-notes")
    now = datetime(2026, 10, 20, tzinfo=UTC)

    assert await maybe_refresh_notes(conn, "u-notes", now=now) is True
    conn.commit()
    state = load_preference_state(conn, "u-notes")
    assert state is not None and state.notes == ["Prefers warm colours."]

    assert await maybe_refresh_notes(conn, "u-notes", now=now + timedelta(days=2)) is False
    assert await maybe_refresh_notes(conn, "u-notes", now=now + timedelta(days=8)) is True


async def test_no_notes_are_written_before_there_is_enough_to_summarise(
    conn: psycopg.Connection[Any], monkeypatch: pytest.MonkeyPatch
) -> None:
    routing.reset_provider_cache()
    monkeypatch.setenv("LLM_PROMPTS", "mock:mock-notes")
    _seed_best_of_three(conn, "u-early", 8, _warmest, np.random.default_rng(2))
    rebuild_preference(conn, "u-early")
    assert (
        await maybe_refresh_notes(conn, "u-early", now=datetime(2026, 10, 20, tzinfo=UTC)) is False
    )
    row = conn.execute("SELECT notes FROM preference_models WHERE user_id='u-early'").fetchone()
    assert row is not None and row["notes"] == {}


def test_picks_on_candidates_from_before_every_option_was_phrased_do_not_teach_the_knob_model(
    conn: psycopg.Connection[Any],
) -> None:
    """The person's real week (generated with a bare "as usual") is not learned from by the knob
    model or counted in the default-pick KPI — but still feeds the ranking model."""
    _seed_best_of_three(conn, "u-old", 40, _warmest, np.random.default_rng(2))
    conn.execute("UPDATE candidates SET scores = scores - 'phrased' WHERE day_id LIKE 'u-old:%'")
    conn.commit()

    summary = rebuild_preference(conn, "u-old")
    conn.commit()

    assert summary["n_taps"] == 40  # the ranking model still sees them
    assert summary["lean"] == {"warmth": 0, "closeness": 0, "expression": 0}
    assert (
        summary["accuracy"]["default_pick"] is None and summary["accuracy"]["default_pick_n"] == 0
    )
    knob = conn.execute("SELECT knobs FROM preference_models WHERE user_id='u-old'").fetchone()
    assert knob is not None and knob["knobs"]["n_taps"] == 0


def test_options_can_share_one_seed_so_they_differ_only_in_their_phrase() -> None:
    plan = plan_for_panel(1)
    same = [variant_prompt(_prompt(), plan, k, same_seed=True)[0] for k in range(3)]
    assert {v.seed for v in same} == {100} and len({v.positive for v in same}) == 3
    apart = [variant_prompt(_prompt(), plan, k)[0] for k in range(3)]
    assert [v.seed for v in apart] == [100, 101, 102]  # the old behaviour is still available


def test_the_ranking_model_learns_a_taste_that_lives_in_the_image_embedding(
    conn: psycopg.Connection[Any],
) -> None:
    """The named features say nothing here (they are random); the picks follow a hidden factor
    that only the image embedding carries. Predicting the favourite of three must beat chance
    (a third) — through the projection stored with the model."""
    _seed_best_of_three(conn, "u-emb", 70, _warmest, np.random.default_rng(5), pick_embedding=True)
    summary = rebuild_preference(conn, "u-emb")
    conn.commit()
    assert summary["accuracy"]["learned"] > 0.6
    row = conn.execute("SELECT embed FROM preference_models WHERE user_id='u-emb'").fetchone()
    assert row is not None and len(row["embed"]["components"]) == 6
    state = load_preference_state(conn, "u-emb")
    assert state is not None and state.projection is not None
    assert len(state.mu) == len(FEATURES)  # trained and loaded with the same feature set


# --- ratings ---------------------------------------------------------------------------------


def _rate_all_by_warmth(conn: psycopg.Connection[Any], user_id: str) -> int:
    """The person rates every image: warm ones great, middling ones ok, cool ones off."""
    rows = conn.execute(
        "SELECT c.day_id, c.panel_id, c.url, (c.scores->>'warmth')::float AS warmth "
        "FROM candidates c JOIN days d ON d.job_id = c.day_id WHERE d.user_id = %s",
        (user_id,),
    ).fetchall()
    for r in rows:
        rating = 2 if r["warmth"] > 0.62 else 1 if r["warmth"] > 0.4 else 0
        conn.execute(
            "INSERT INTO image_ratings (day_id, panel_id, url, rating) VALUES (%s,%s,%s,%s)",
            (r["day_id"], r["panel_id"], r["url"], rating),
        )
    conn.commit()
    return len(rows)


def test_ratings_teach_the_model_what_a_good_image_is_and_where_the_cut_points_sit(
    conn: psycopg.Connection[Any],
) -> None:
    _seed_best_of_three(conn, "u-rate", 30, _warmest, np.random.default_rng(3))
    n_rated = _rate_all_by_warmth(conn, "u-rate")

    summary = rebuild_preference(conn, "u-rate")
    conn.commit()

    ratings = summary["accuracy"]["ratings"]
    assert ratings["n"] == n_rated == 90
    assert ratings["great"] + ratings["ok"] + ratings["off"] == 90 and ratings["great"] > 0
    low, high = ratings["thresholds"]
    assert low < high  # "ok" starts below "great"
    row = conn.execute("SELECT mu FROM preference_models WHERE user_id='u-rate'").fetchone()
    assert row is not None and len(row["mu"]) == len(
        FEATURES
    )  # cut points are not stored as features
    weights = dict(zip(FEATURES, row["mu"], strict=True))
    assert weights["warmth"] == max(weights.values()) and weights["warmth"] > 0.5


def test_ratings_alone_are_enough_to_learn_from_and_never_crash_a_rebuild(
    conn: psycopg.Connection[Any],
) -> None:
    _seed_best_of_three(conn, "u-only-rate", 12, _warmest, np.random.default_rng(3))
    conn.execute(
        "DELETE FROM image_pairs "
        "WHERE day_id IN (SELECT job_id FROM days WHERE user_id = 'u-only-rate')"
    )
    _rate_all_by_warmth(conn, "u-only-rate")
    summary = rebuild_preference(conn, "u-only-rate")
    assert summary["n_taps"] == 0 and summary["accuracy"]["ratings"]["n"] == 36
    row = conn.execute("SELECT mu FROM preference_models WHERE user_id='u-only-rate'").fetchone()
    assert row is not None and abs(dict(zip(FEATURES, row["mu"], strict=True))["warmth"]) > 0.1


def test_only_the_latest_rating_of_an_image_counts(conn: psycopg.Connection[Any]) -> None:
    _seed_best_of_three(conn, "u-mind", 3, _warmest, np.random.default_rng(3))
    job = "u-mind:0"
    url = f"http://x/{job}-2.png"
    for rating in (0, 2):  # first "off", then changes their mind to "great"
        conn.execute(
            "INSERT INTO image_ratings (day_id, panel_id, url, rating) VALUES (%s,1,%s,%s)",
            (job, url, rating),
        )
    conn.commit()
    ratings = rebuild_preference(conn, "u-mind")["accuracy"]["ratings"]
    assert (ratings["n"], ratings["great"], ratings["off"]) == (1, 1, 0)


def test_rounds_drawn_by_the_bandit_feed_its_posterior_and_the_feel_good_term(
    conn: psycopg.Connection[Any],
) -> None:
    _seed_best_of_three(conn, "u-ts", 15, _warmest, np.random.default_rng(2), roles=True)
    rebuild_preference(conn, "u-ts")
    conn.commit()
    row = conn.execute("SELECT knobs FROM preference_models WHERE user_id='u-ts'").fetchone()
    assert row is not None
    posterior = row["knobs"]["ts"]
    assert len(posterior["mu"]) == 6 and len(posterior["center_mu"]) == 6
    assert set(posterior["other_arm"]) == {"1", "2"} and len(posterior["other_arm"]["1"]) == 15
    state = load_preference_state(conn, "u-ts")
    assert state is not None and state.bandit is not None and state.knob_taps == 15
    # tempered (each row counts for ETA of a comparison): wider than the plain posterior
    plain_sd = np.sqrt(np.diag(np.array(row["knobs"]["cov"])))
    tempered_sd = np.sqrt(np.diag(state.bandit.cov))
    assert np.all(tempered_sd >= plain_sd - 1e-9) and np.any(tempered_sd > plain_sd * 1.05)
